# Generated by Django 5.0.6 on 2026-05-20 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('hospital', 'Hospital'), ('legal_aid', 'Legal Aid'), ('emergency', 'Emergency Services'), ('shelter', 'Shelter'), ('other', 'Other')], default='other', max_length=12)),
                ('location', models.TextField(blank=True, help_text='Resource location (WGS84). Required for proximity queries.', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Whether this resource is currently operational.')),
                ('contact_info', models.JSONField(blank=True, default=dict, help_text='E.g. {"phone": "+91-...", "email": "..."}')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible resource-specific data (beds, jurisdiction, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['resource_type', 'is_available'], name='resources_r_resourc_5cdf7f_idx')],
            },
        ),
    ]
