# Generated by Django 5.0.6 on 2026-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=models.JSONField(blank=True, help_text='Fallback: store as {lat, lng} when GDAL unavailable', null=True),
        ),
    ]
