# Generated by Django 5.0.6 on 2026-05-20 11:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text="Description of the action (e.g. 'incident_created', 'status_changed').", max_length=255)),
                ('performed_by', models.CharField(help_text='User, agent name, or system component that performed the action.', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the action.')),
                ('hash', models.CharField(editable=False, help_text='SHA-256 of (incident_id + action + performed_by + timestamp).', max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['timestamp'],
            },
        ),
    ]
