# Generated by Django 5.0.6 on 2026-05-20 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField(blank=True, help_text='Raw text content of the signal.')),
                ('image', models.ImageField(blank=True, help_text='Optional image attachment.', null=True, upload_to='signals/images/%Y/%m/')),
                ('source_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('webhook', 'Webhook')], default='text', max_length=10)),
                ('location', models.TextField(blank=True, help_text='Geographic origin of the signal (WGS84).', null=True)),
                ('domain', models.CharField(blank=True, choices=[('legal', 'Legal'), ('health', 'Health'), ('emergency', 'Emergency'), ('cross', 'Cross-domain')], help_text='Classified domain — set by the pipeline after ingestion.', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary extra data from the ingestion source.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Signal',
                'verbose_name_plural': 'Signals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='signals_sig_tenant__0e05c3_idx'), models.Index(fields=['domain'], name='signals_sig_domain_eb1161_idx')],
            },
        ),
    ]
