# Generated by Django 5.0.6 on 2026-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Optional contact number for updates.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='location',
            field=models.JSONField(blank=True, help_text='Fallback: store as {lat, lng} when GDAL unavailable', null=True),
        ),
    ]
