# Generated by Django 5.0.6 on 2026-05-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_signal_contact_number_alter_signal_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='preferred_language',
            field=models.CharField(blank=True, default='hindi', help_text='Citizen preferred language for report translation', max_length=20),
        ),
    ]
