# Generated by Django 5.0.6 on 2026-08-30 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_signal_preferred_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The citizen account that owns this signal report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to=settings.AUTH_USER_MODEL),
        ),
    ]
