# Generated by Django 5.0.6 on 2026-08-31 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_signal_user'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['user', '-created_at'], name='signals_sig_user_id_c6184e_idx'),
        ),
    ]
