# Generated by Django 5.0.6 on 2026-05-20 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity_score', models.FloatField(default=0.0, help_text='Normalised severity in [0.0, 1.0] assigned by SentinelAgent.')),
                ('severity_label', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('domain', models.CharField(blank=True, choices=[('legal', 'Legal'), ('health', 'Health'), ('emergency', 'Emergency'), ('cross', 'Cross-domain')], max_length=10)),
                ('agent_outputs', models.JSONField(blank=True, default=dict, help_text='Structured outputs from all agents, keyed by agent name. Example: {"sentinel": {...}, "rights": {...}}')),
                ('situation_brief', models.TextField(blank=True, help_text='Plain-language situation summary produced by LanguageAgent.')),
                ('recommended_resources', models.JSONField(blank=True, default=list, help_text='List of recommended resource IDs from CoordinationAgent.')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incident', to='signals.signal')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_resolved'], name='incidents_i_is_reso_d161de_idx'), models.Index(fields=['severity_label'], name='incidents_i_severit_58670c_idx'), models.Index(fields=['domain'], name='incidents_i_domain_22212e_idx')],
            },
        ),
    ]
