# Generated by Django 5.0.6 on 2026-05-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='coordinator_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='coordinator_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('action_taken', 'Action Taken'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
