# Generated by Django 5.0.6 on 2026-05-23 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0002_signal_contact_number_alter_signal_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_number', models.CharField(help_text='Target phone number for simulated SMS.', max_length=15)),
                ('message_english', models.TextField(help_text='Synthesized English message.')),
                ('message_hindi', models.TextField(help_text='Translated Hindi message.')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of simulated dispatch.')),
                ('status', models.CharField(default='sent', help_text='Notification delivery status.', max_length=20)),
                ('signal', models.ForeignKey(help_text='The signal this notification belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='signals.signal')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
